### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Nephanor-of-Fraal** [baphilia/SillyTavernAutoExpressions#1]
I likely missed something in my python install on windows, but I cannot drop the images into the .py file.  I tried making it an .exe with PyInstaller and no luck with that either.

**Comment by baphilia** [comment]
I haven't had a chance to investigate this yet, but certain cards aren't working for the card version.  Busy with dayjob stuff at the moment so not sure when I will be able to get to it, but did you try the image version and that didn't work as well?  That one works for me for the ones that don't work with the card version.

**Comment by baphilia** [comment]
> I likely missed something in my python install on windows, but I cannot drop the images into the .py file. I tried making it an .exe with PyInstaller and no luck with that either.

I believe it's fixed now, btw.  if so, please close this bug.  thanks for the bug report!

**Comment by Nephanor-of-Fraal** [comment]
Not working for me.  I haven't tried using PyInstaller.  Is there a setting in python/windows that I need to have to allow dropping files into .py files?

**Comment by baphilia** [comment]
> Not working for me. I haven't tried using PyInstaller. Is there a setting in python/windows that I need to have to allow dropping files into .py files?

if you don't mind, please try again with the updated version.  I removed a dependency from the card version.  So, to be clear neither version worked for you (DefaultExpressionsFromCard.py or DefaultExpressionsFromAnyImage.py)?

if it still is not working please run it like this:
python DefaultExpressionsFromCard.py yourCardFile.png

and paste any errors you get here.  Thank you.

**Comment by Nephanor-of-Fraal** [comment]
Well, I can run it one at a time from the console, but not dropping them in....yikes, this is gonna take a while.  And yeah neither of them worked

**Comment by baphilia** [comment]
> Well, I can run it one at a time from the console, but not dropping them in....yikes, this is gonna take a while. And yeah neither of them worked

Gimme a few.  I'll make a way to do the entire folder at least.

**Comment by baphilia** [comment]
> Well, I can run it one at a time from the console, but not dropping them in....yikes, this is gonna take a while. And yeah neither of them worked

Please download the new version of DefaultExpressionsFromCard.py

To use on all files in directory, open a cmd prompt in the characters directory and run 
```
python DefaultExpressionsFromCard.py --all
```

**Comment by Nephanor-of-Fraal** [comment]
Got partway through and then this error:

Traceback (most recent call last):
  File "C:\Users\nepha\SillyTavern-main\public\characters\DefaultExpressionsFromCard.py", line 81, in <module>
    process_all_files_in_directory()
  File "C:\Users\nepha\SillyTavern-main\public\characters\DefaultExpressionsFromCard.py", line 76, in process_all_files_in_directory
    process_file(file_name)
  File "C:\Users\nepha\SillyTavern-main\public\characters\DefaultExpressionsFromCard.py", line 66, in process_file
    shutil.copy2(file_path, new_file_path)
  File "C:\Program Files\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python311\Lib\shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nepha\\SillyTavern-main\\public\\characters\\Bianca \\admiration.png'

**Comment by Nephanor-of-Fraal** [comment]
Seems it was an issue with the PNG file.  I removed it and it worked fine.  Thanks!  Closing
